version: '3.3'
services:


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:  # dataset password
      MYSQL_DATABASE: test_database
      MYSQL_USER: amir
      MYSQL_PASSWORD: Amir12345
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  my-app:
    build: . 
    container_name: gpt-container
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8080", "--reload" ]
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mysql+pymysql://amir:datasetpasswrod/test_database"  
      UPLOAD_DIR: "upload"
      MAIN_DIR: "app"
      USER_AGENT: "myagent"
      TAVILY_API_KEY: # TAVILY_API_KEY
      GROQ_API_KEY: # GROQ_API_KEY
      FLASK_APP: app/server
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      - db
    networks:
      - my_network

  
volumes:
  db_data:

networks:
  my_network: