version: '3.1'
services:
  my-app:
    build: . 
    container_name: gpt-container
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8080", "--reload" ]
    ports:
      - 8080:8080
    environment:
      GROQ_API_KEY: YOUR_GROQ_API_KEY
      FLASK_APP: app/server
      FLASK_ENV: development